/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
    "./index.tsx"
  ],
  darkMode: 'class',
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    // Safelist color variations used dynamically in getColorClasses()
    // Note: dark mode variants are auto-generated by Tailwind when base classes are safelisted
    {
      pattern: /^bg-(sky|green|amber|rose|indigo|teal|fuchsia|slate)-100$/,
      variants: ['dark'],
    },
    {
      pattern: /^bg-(sky|green|amber|rose|indigo|teal|fuchsia|slate)-500$/,
      variants: ['dark'],
    },
    {
      pattern: /^text-(sky|green|amber|rose|indigo|teal|fuchsia|slate)-300$/,
      variants: ['dark'],
    },
    {
      pattern: /^text-(sky|green|amber|rose|indigo|teal|fuchsia|slate)-700$/,
      variants: ['dark'],
    },
    {
      pattern: /^border-(sky|green|amber|rose|indigo|teal|fuchsia|slate)-400$/,
      variants: ['dark'],
    },
    {
      pattern: /^border-(sky|green|amber|rose|indigo|teal|fuchsia|slate)-500$/,
      variants: ['dark'],
    },
  ],
}